# Generated by Django 4.2.5 on 2023-09-30 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_payments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'ordering': ['-payment_date'], 'verbose_name': 'платеж', 'verbose_name_plural': 'платежи'},
        ),
    ]
