# Generated by Django 4.2.5 on 2023-10-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_author_lesson_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=25, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=25, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_way',
            field=models.CharField(choices=[('cash', 'paid_by_cash'), ('transaction', 'paid_by_transaction')], max_length=12, verbose_name='способ оплаты'),
        ),
    ]
